name: Increment version

on:
  workflow_dispatch:
    inputs:
        latest-version:
            description: "Lateset version"
            required: false
        default-release-type:
            description: |
                Default release type will be applied if a release type label is not selected.
                If this field is not configured and a release type label is not selected the action will fail.
        required: false
    outputs:
      release-type:
        description: "Release type selected from the PR labels"
      new-version:
        description: "New version after semver increment"

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Run Increment Script
        runs:
          using: "node16"
          main: "./inc.js"

