name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}
