name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}

      - name: Configure git
        run: |
          git config user.name "Oleksandr Filshyn"
          git config user.email "host.sf@gmail.com"

      - name: Get latest tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "current_tag=$(gh release list | grep Latest | awk '{print $1}')" > $GITHUB_ENV

      - name: Increment version
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            gh workflow run increment-version.yml

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
#
#       - name: Install dependencies
#         run: yarn install --frozen-lockfile
#
#       - name: Bump versions
#         env:
#           REPO_VERSION: ${{ steps.increment-version.outputs.new-version }}
#         run: |
#           yarn nx affected --target=bump-version --base=${{env.current_tag}} --head=HEAD
#
#       - name: Push changes
#         run: |
#           git add -A
#           git commit --allow-empty -m "Bump affected package versions" --no-verify
#           git push origin master
#
#       - name: Create release and trigger publish
#         env:
#           PREVIOUS_TAG: ${{env.current_tag}}
#           TAG: v${{ steps.increment-version.outputs.new-version }}
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           gh release create $TAG --generate-notes
